version: '3.8'
services:
  book-store-db:
    container_name: book-store-db
    image: mongo:6
    ports:
      - '27017:27017'
    volumes:
      - type: bind
        source: ./mongo-data
        target: /data/db
  message-broker:
    container_name: message-broker
    image: rabbitmq:3.12-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    hostname: 'localhost'
    volumes:
      - type: bind
        source: ./message-broker-data
        target: /var/lib/rabbitmq/mnesia/rabbit@localhost
volumes:
  mongo-data:
  message-broker-data:
