$(npm bin)/ts-node 02-work-queues/new-task.ts First.
$(npm bin)/ts-node 02-work-queues/new-task.ts Second..
$(npm bin)/ts-node 02-work-queues/new-task.ts Third...
$(npm bin)/ts-node 02-work-queues/new-task.ts Fourth....
$(npm bin)/ts-node 02-work-queues/new-task.ts Fifth.....
