services:
  book-store-db:
    container_name: book-store-db
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
  message-broker:
    container_name: message-broker
    image: rabbitmq:4-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
volumes:
  mongo-data:
